// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jbpwgvjlvrpxwumxrnmm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpicHdndmpsdnJweHd1bXhybm1tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0NjQ3OTMsImV4cCI6MjA1NjA0MDc5M30.vaKyeaQV7mkKT5mZgFivRjS1H_X7pHK2dRDhGOcF_Z0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);